### ISSUE TITLE
Upgrade docker java

### ISSUE THREAD

**Issue by Thorndike** [alexec/docker-java-orchestration#93]
Please Upgrade the Version of docker-java to at least 3.0.10 to be able to build with current versions of docker.

https://github.com/docker-java/docker-java/issues/830

And as a consequence release a new version of the maven plugin.

**Comment by alexec** [comment]
3.0.10 not yet released.

**Comment by marcust** [comment]
But now it is https://github.com/docker-java/docker-java/releases/tag/3.0.10

**Comment by gsaviane** [comment]
Hi,
  I gave it a try and it seems to be working fine.
1. I cloned docker-java-orchestration and changed the reference to docker-java v 3.0.11. Compilation and test ok.
2. I cloned docker-maven-plugin and changed the reference to docker-java-orchestration SNAPSHOT above. Compilation and test ok.
3. I linked my project to the updated docker-maven-plugin above and now the test phase does not brake anymore because of this:
https://github.com/docker-java/docker-java/issues/830

Do you have a plan to release an update for the orchestrator and maven plugin in the short term?

**Comment by alexec** [comment]
I'm looking to avoid spending a great deal of time maintaining this plugin anymore. 

Please see this ticket for alternatives: https://github.com/alexec/docker-maven-plugin/issues/118

**Comment by gsaviane** [comment]
Yea, ok. But at least we can manage to have our integration test platform running while we migrate to the alternative plugin.

**Comment by alexec** [comment]
I can still release changes, but I don't want to spend too much time on it. If you submit a PR, I'll release it.

**Comment by gsaviane** [comment]
I saw your commits. Do you still need the PR?

**Comment by alexec** [comment]
The release should be in Maven central in 24 hours.

**Comment by gsaviane** [comment]
Thanks!
